echo Starting Tailscale (forwarder)...
start "Tailscale" tailscale funnel 5000
echo Waiting 5 seconds (incase tailscale delays a bit)...
TIMEOUT /T 5 /NOBREAK
echo Starting Flask (server)...
start "Flask" py server.py
echo Should be ready!
pause